version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      base-image:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-patch:
        update-types:
          - minor
          - patch
