ARG PYTHON_VERSION=3.14
FROM ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-trixie-slim AS builder

WORKDIR /app

ENV UV_LINK_MODE=copy

COPY pyproject.toml uv.lock .python-version ./
COPY src ./src
COPY test ./test

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --group test --no-install-project

ARG PYTHON_VERSION=3.14
FROM python:${PYTHON_VERSION}-slim

WORKDIR /app

ENV PYTHONPATH=/app:/app/src

COPY --from=builder /app/.venv /app/.venv
COPY src ./src
COPY test ./test
COPY pyproject.toml ./


ENV PATH="/app/.venv/bin:$PATH"

CMD ["pytest"]
